# Generated by Django 4.1.6 on 2023-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('med_salary', models.FloatField(verbose_name='Зарплата')),
                ('vac_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('med_salary_python', models.FloatField(null=True, verbose_name='Зарплата по выбранной профессии')),
                ('vac_count_python', models.IntegerField(null=True, verbose_name='Количество вакансий по выбранной профессии')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованность',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('med_salary', models.FloatField(verbose_name='Мединаная зарплата')),
                ('vac_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
    ]
